### ISSUE TITLE
Handle missing body in a basic section

### ISSUE THREAD

**Issue by raae** [olavea/pow-site#23]
What happens if someone does not add body? Take a look at that and come up with solution so it does not break.

_Originally posted by @raae in https://github.com/olavea/pow-site/pull/21#discussion_r804579073_

**Comment by olavea** [comment]
```js
// pages / {MarkdownRemark.fields__slug}.js
const { html } = section.body.childMarkdownRemark || [];
```

**Comment by olavea** [comment]
I did another rep on this 💪 😺 👍
