### ISSUE TITLE
Add support for images in markdown content

### ISSUE THREAD

**Issue by raae** [olavea/pow-site#66]
Add [gatsby-remark-images](https://www.gatsbyjs.com/plugins/gatsby-remark-images/) (follow link for instructions).

Definition of done when blog image shows up at `/blog/peek-a-boo-component/`:
- ie. http://localhost:8000/blog/peek-a-boo-component/ locally

**Comment by olavea** [comment]
```shell
yarn add gatsby-remark-images gatsby-plugin-sharp

I got this ERROR
[========================    ]   58.654 s 6/7 86% Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs
^C
 ERROR 

There was an unhandled error and we could not retrieve more information. Please run the command with the --verbose flag again.

not finished Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs - 458.688s

 ERROR 
````
Because I forgot to do this 😆 :

```js
// gatsby-config.js

          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 1333,
            },
          },
```

Now it's all good! 😺 👍 
![gatsby-remark-images](https://user-images.githubusercontent.com/7642493/165927506-aafc813c-97c5-4129-a4d5-b08ee0c645b6.png)
