### ISSUE TITLE
Redirect from /login to my.usepow.app

### ISSUE THREAD

**Issue by raae** [olavea/pow-site#67]

**Comment by olavea** [comment]
Hmm....

How would you recommend I do this?

**Comment by raae** [comment]
I would do option 2 in this blog @olavea

**Comment by olavea** [comment]
I cannot see the link @raae

**Comment by raae** [comment]
Here you go https://levelup.gitconnected.com/how-to-add-netlify-redirects-to-a-gatsby-site-ae678518cc91
